### ISSUE TITLE
Remove or add class to <span>

### ISSUE THREAD

**Issue by ahstro** [socialtables/react-image-fallback#12]
If people have styled `span` tags where using `react-image-fallback`, there's currently no simple way to unstyle the `span` surrounding the `img`.
I would suggest removing it or, if there's a good reason for it being there, add a class to it, so that it can easily be unstyled with CSS.
I would've made a PR, but I wanted to discuss which alternative is better first.

**Comment by conorhastings** [comment]
i think the span can be removed, would accept a PR.
