### ISSUE TITLE
fallbackImage as array?

### ISSUE THREAD

**Issue by mbrevda** [socialtables/react-image-fallback#33]
Would it be possible to convert `fallbackImage` to an array, so that we can have multiple fallbacks? In case the first is missing, try the second, etc...

**Comment by mattaningram** [comment]
This was originally a feature but was then removed for some reason (probably harder to do than it seems). I do hope they bring it back, we had a great equivalent in Angular.

**Comment by conorhastings** [comment]
@mbrevda @mattaningram Thanks for the feedback! The previous implementation never really worked and was reverted pretty quickly. We never really used it internally so didn't have a need to focus on it but I had some time tonight and was able to implement. Passing `fallbackImage` as an array should be available in `3.2.0`

**Comment by mattaningram** [comment]
That was awesomely fast @conorhastings thanks for all your hard work!

**Comment by mbrevda** [comment]
Thanks! One more note: perhaps it would make sense to just pass the array
as srcImage, with no need for a separate property for the fallback...

**Comment by conorhastings** [comment]
@mbrevda I think that potentially I would like to support arrays for both, but don't neccesarily think we'll deprecate fallbackImage as some may prefer that api.

**Comment by mbrevda** [comment]
I've gone ahead and released my own lib which supports multiple fallbacks: https://www.npmjs.com/package/react-image

Thanks!
