### ISSUE TITLE
Exception during initial render is hidden by exception in react-image-fallback 'componentWillUnmount'

### ISSUE THREAD

**Issue by relefant** [socialtables/react-image-fallback#43]
Version 6.0.0

If the initial react tree fails to render due to an exception (i.e. uncaught exception thrown from render() of one of the React components), it can be that `componentWillUnmount` is called without having called `componentDidMount`.

This causes `this.displayImage` in `componentWillUnmount` to be undefined and therefore cause an error that masks the original error (stops the React error html from rendering).

A fix would be to surround the clean up with a null check:

```
if (this.displayImage) {
	this.displayImage.onerror = null;
	this.displayImage.onload = null;
	this.displayImage = null;
}
```

**Comment by conorhastings** [comment]
@relefant would you willing be to make a pr for this?

**Comment by relefant** [comment]
@conorhastings sure.

**Comment by conorhastings** [comment]
@relefant great, appreciate it
