### ISSUE TITLE
Allow initial display to be a component

### ISSUE THREAD

**Issue by conorhastings** [socialtables/react-image-fallback#8]
Use Case: Css animation to display before an image loads, instead of an image that will also have to load.

**Comment by conorhastings** [comment]
or a function that returns a component?

**Comment by conorhastings** [comment]
probablya  component

**Comment by rickyvetter** [comment]
Wouldn't it make sense to make the final fallback a component as well?

**Comment by conorhastings** [comment]
it should definitely be an option

**Comment by conorhastings** [comment]
more of an issue for intital display though, because you want something to lbe there imediately i

**Comment by rickyvetter** [comment]
I think it might actually be a bigger deal for fallbacks in case of no connection. But regardless, it's would be cool for both :)

**Comment by conorhastings** [comment]
true true true true true
